INSERT INTO pengguna (nama, email, passwords, created_at, updated_at) 
VALUES
('Siti Aminah', 'sitiam@example.com', 'password123', DEFAULT, DEFAULT),
('Ahmad Fadillah', '[email address removed]', 'password123', DEFAULT, DEFAULT),
('Dewi Kurniasih', 'dewi@example.com', 'password123', DEFAULT, DEFAULT),
('Budi Santoso', 'budi@example.com', 'password123', DEFAULT, DEFAULT),
('Ani Setiawati', 'ani@example.com', 'password123', DEFAULT, DEFAULT),
('Agus Susilo', 'agus@example.com', 'password123', DEFAULT, DEFAULT),
('Olivia Asmara', 'olivia@example.com', 'password123', DEFAULT, DEFAULT),
('Yoga Pratama', 'yogapratm@example.com', 'password123', DEFAULT, DEFAULT),
('Marta Widiastuti', 'marta@example.com', 'password123', DEFAULT, DEFAULT),
('Teguh Yulianto', 'teguh@example.com', 'password123', DEFAULT, DEFAULT),
('Ferdi Wulandari', 'ferdi@example.com', 'password123', DEFAULT, DEFAULT),
('Sari Handayani', 'sari@example.com', 'password123', DEFAULT, DEFAULT),
('Joni Setiawan', 'joni@example.com', 'password123', DEFAULT, DEFAULT),
('Erna Susanti', 'erna@example.com', 'password123', DEFAULT, DEFAULT),
('Edo Permana', 'edo@example.com', 'password123', DEFAULT, DEFAULT),
('Rita Hartati', 'rita@example.com', 'password123', DEFAULT, DEFAULT),
('Nia Rahmawati', 'nia@example.com', 'password123', DEFAULT, DEFAULT),
('Bayu Maulana', 'bayu@example.com', 'password123', DEFAULT, DEFAULT),
('Galang Hermawan', 'galang@example.com', 'password123', DEFAULT, DEFAULT),
('Herlina', 'herlina@example.com', 'password123', DEFAULT, DEFAULT),
('Siti Nurjanah', 'sitinur@example.com', 'password123', DEFAULT, DEFAULT),
('Yoga Rizqiana', 'yogariz@example.com', 'password123', DEFAULT, DEFAULT),
('Muhammad Iqbal', 'muhammad@example.com', 'password123', DEFAULT, DEFAULT),
('Fina Lestari', 'fina@example.com', 'password123', DEFAULT, DEFAULT),
('Diki Permana', 'diki@example.com', 'password123', DEFAULT, DEFAULT),
('Jona Suprapto', 'jona@example.com', 'password123', DEFAULT, DEFAULT),
('Rudi Hartono', 'rudi@example.com', 'password123', DEFAULT, DEFAULT),
('Ati Nurdiana', 'ati@example.com', 'password123', DEFAULT, DEFAULT),
('Judi Maulana', 'judi@example.com', 'password123', DEFAULT, DEFAULT),
('Denny Susanto', 'denny@example.com', 'password123', DEFAULT, DEFAULT),
('Prabowo Subianto', 'prabowo@example.com', 'password123', DEFAULT, DEFAULT);